:imagesdir: ./docs/images

= "Build Your First PWA"

:linkattrs:

This repo is intended to be used as a starter project for the Enonic meetup "Build Your First PWA"

== Slides

http://slides.com/alan_semenov/enonic-workshop-pwa

== Installation

1.Make sure you have Enonic XP of version 6.12 or later installed locally. If not, http://xp.readthedocs.io/en/stable/getstarted/other.html#download-enonic-xp[read how to install it here]:

2.Set up environment variable XP_INSTALL that points to the XP installation folder:

==== OSX/Linux

`export XP_INSTALL=/Users/ase/Downloads/enonic-xp-6.13.0-SNAPSHOT`

==== Windows

`set XP_INSTALL=/Users/ase/Downloads/enonic-xp-6.13.0-SNAPSHOT`

3.Create a new folder for your application

4.Initialize the app based on this Starter kit by running the following command (for more info on project initialisation,
read http://xp.readthedocs.org/en/stable/reference/toolbox/init-project.html[the documentation for init-project])

==== OSX/Linux

`$XP_INSTALL/toolbox/toolbox.sh init-project -n com.company.myapp -r starter-pwa`

==== Windows

`$XP_INSTALL/toolbox/toolbox.bat init-project -n com.company.myapp -r starter-pwa`

TIP: Replace ``com.company.myapp`` with a unique name of your app.

5.You can now build the app by running the following from inside the app's folder:
[source,groovy]
----
gradlew build deploy
----

6.If the build completed without errors you will have a new jar file in the `<$XP_INSTALL>/home/deploy` folder.

